name: falcon_corona_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  sqflite: ^1.3.0
  path: ^1.6.4
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.25+3
  location: ^3.0.2
  firebase_database: ^3.1.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
