name: falcon_corona_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  path: ^1.6.4
  firebase_database: ^3.1.3
  http: ^0.12.0+4
  uuid: ^2.0.4
  shared_preferences: ^0.5.6+3
  google_maps_flutter: ^0.5.25+3
  flutter_circular_chart: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.0.0
  webview_flutter: ^0.3.19+9
  flutter_share: ^1.0.2+1
  flutter_spinkit: ^4.1.2
  shimmer: ^1.1.1
  foreground_service: ^2.0.0
  geolocator: ^5.3.1
  cupertino_icons: ^0.1.2
  location: ^3.0.2
  permission_handler: ^5.0.0+hotfix.3
  fancy_on_boarding: ^1.6.0
  tutorial_coach_mark: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
