name: falcon_corona_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  path: ^1.6.4
  firebase_database: ^3.1.3
  http: ^0.12.0+4
  uuid: ^2.0.4
  shared_preferences: ^0.5.6+3
  google_maps_flutter: ^0.5.25+3
  foreground_service: ^1.1.5
  geolocator: ^5.3.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
